### ISSUE TITLE
Feature request: принудительная замена файла симлинком.

### ISSUE THREAD

**Issue by webarchitect609** [somework/composer-symlinks#1]
Игорь, хочется опцию принудительной замены файла симлинком. По умолчанию такого поведения нет и даже утилита `ln` не заменяет существующий файл/папку на симлинк. Но есть случаи, когда надо. 

Например, у нас есть `/bitrix/.settings.php`, но `/bitrix/` под игнором и мы заводим `/local/.settings.php`, который Битрикс искать не будет. Поэтому требуется заменить файл `/bitrix/.settings.php` на симлинк, ведущий `../local/.settings.php`

А так идея пакета классная!

**Comment by somework** [comment]
Спасибо!
Сделаем!

**Comment by somework** [comment]
Релизовано в версии 1.1
